apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-backend
  namespace: argocds
spec:
  project: default
  source:
    repoURL: 'https://github.com/Dhanush19B61A0550/gitOps-backend.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
